import { Typography } from '@mui/material';
import Head from 'next/head';
import styles from '../styles/Home.module.css';


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kristen&apos;s Vintage Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <Typography>Future Home of Kristen&apos;s Vintage Home</Typography>
      </main>
    </div>
  );
}
